### ISSUE TITLE
[SSW] Harjel III conflicts with itself.

### ISSUE THREAD

**Issue by Nehvar** [Solaris-Skunk-Werks/solarisskunkwerks#107]
If you try to add multiple Harjel III systems to a 'mech one at a time you are met with a conflict message (see image).  There is a work-around however.  You can still use the drop-down to add multiple Harjel III systems at once.

![Harjel3](https://user-images.githubusercontent.com/59345488/71703406-56a7a280-2da2-11ea-9f21-5bf9e7d0e19a.jpg)

**Comment by Maelwys** [comment]
I wonder if this could be an artifact of the "Exceptions" Column in the Equipment.ods file.

HarJel III should have an exception of HarJel II (and maybe just Harjel as well, will have to check the rules). So is it possible some weird naming issue is happening?

Although if it is some weird naming issue that's happening, it would mean the current work around (using the dropdown to add multiples at once) would be an incorrect behavior since it would let you get around what is normally a properly working restriction).

**Comment by WEKarnesky** [comment]
@Maelwys If you could do research on the specific rules and exceptions, then report back, I'd appreciate it.  I'll look into the possible solutions while you do that.

Given there is a workaround, I'm marking this as low priority, but fixing low hanging fruit still usually gets done before new features.

**Comment by WEKarnesky** [comment]
hrm... my guess is that this is a parsing issue of the exclusions.  The rest of the HarJels will also have to be updated too.  

![image](https://user-images.githubusercontent.com/8506084/71705865-54d7e200-2d96-11ea-8bc5-d1de32ba765e.png)

**Comment by Maelwys** [comment]
Yeah, I think I'll have to check with CGL and see if Harjel counts as HarJel...

**Comment by Maelwys** [comment]
So this interesting. The workaround is indeed a break. 

For example, you can only have 1 Radical Heat Sink. Normally if you just try to add them one at a time, you'll get an error message saying that you can only mount 1.

However, SSW will allow you to add multiple of the same item at the same time using the little dropdown numberbox next to the clear button. So odd little behavior there.

Right now if we can get the parsing working, then it should be right, though there's some thought that HarJel can go on a mech with HarJEl II or III, but not in the same location.

**Comment by Algebro7** [comment]
Should be closed via #159
