### ISSUE TITLE
BFB Unit Roster doesn't adjust long text

### ISSUE THREAD

**Issue by Notsonoble** [Solaris-Skunk-Werks/solarisskunkwerks#115]
![namebug](https://user-images.githubusercontent.com/3661017/72842855-ebddde80-3c5e-11ea-8278-79dcc6c3786f.png)
**Describe the bug**

The roster page does not handle long names of units or pilots/mechwarriors well. It writes on top of the next column.

**To Reproduce**
1. Go to BFB, create a roster with a long name for mechwarrior/pilot or use a long named unit (the avenging angel vindicator's in the image.
2. Click on Print, include unit roster

**Expected behavior**

Text wrapping, or font scaling, or anything really.

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Ubuntu and Windows
 
**Additional context**

**Comment by Algebro7** [comment]
The problem is at **https://github.com/Solaris-Skunk-Werks/solarisskunkwerks/blob/be0014cd0765f657a52e8873d62483c2855390cb/sswlib/src/main/java/Force/Unit.java#L498**

There is a helper function in `PrintConsts.wrapText()`, which accepts a length and splits a string into a list of strings of the given length. In this case, the columns are 25 characters. It shouldn't be too hard to apply that here to wrap the lines at 25 characters if anyone wants to take a stab at it.
