### ISSUE TITLE
SAW and SSW Select Units Issue

### ISSUE THREAD

**Issue by Maelwys** [Solaris-Skunk-Werks/solarisskunkwerks#135]
In both SAW and SSW, if you go to the "Select Units" screen and then change the view from Total Warfare Standard to "Battleforce Information" the screen seems to freeze and throw out graphical glitches.

The other three choices seem to work fine.

**Comment by Maelwys** [comment]
FWIW, I just checked with 6.82.1 and it does the same thing, so its not something that just popped up.

**Comment by olaughlj** [comment]
What kind of glitches and how long does it seem to freeze? I quickly ran a build from my branch on my Windows 10 Machine as well as 0.6.83.1 and didn't see anything out of the ordinary in SSW and SAW:

![image](https://user-images.githubusercontent.com/6819344/79288213-23da7380-7e94-11ea-9864-920ed69b5392.png)

![image](https://user-images.githubusercontent.com/6819344/79288154-01e0f100-7e94-11ea-9697-92d01abad530.png)

I also tried in an Ubuntu 18.10 VM and openJDK-14 and it seemed not to freeze the table had a redrawing issue but I think that was due to the ESXi display and not particularly SSW related.

**Comment by WEKarnesky** [comment]
This is what I get in SAW, I was unable to reproduce in SSW

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

![image](https://user-images.githubusercontent.com/8506084/79289077-37c6ab00-7e7d-11ea-8f7b-f15e56d464fe.png)

**Comment by olaughlj** [comment]
Ok I will play around with it a little more and see what I can find out.

**Comment by Maelwys** [comment]
Y'all are much quicker than I on cutting and pasting.

I could've sworn SSW did it as well, but can't seem to reproduce it to the extent. The best I get is little ghosts in the slider bar if I try spamming it up an down really quickly, but that just might be the system.

**Comment by gblouin** [comment]
Hmm there isn't a lot going on in these views that you are switching between.  But, we could instantiate the two views when the dialog opens and then just switch between them so that the program isn't constantly re-instantiating (and taking more memory) each time you switch.
