### ISSUE TITLE
Generator key in .mtf output

### ISSUE THREAD

**Issue by IsaBison** [Solaris-Skunk-Werks/solarisskunkwerks#255]
I've proposed a `Generator` key for the .mtf file format and am linking here because it'd basically be a group effort. 

https://github.com/MegaMek/megameklab/issues/1061#issue-1167312529

**Comment by gblouin** [comment]
I am adding Generator: to the output and will have it take place of the existing "Version: 1.1" that is hard coded and gives less value then the new field will.   I am also fixing the SAW output so that it actually produces the file but will probably need to tweak the logic more as we figure out what it SHOULD look like.
