### ISSUE TITLE
Add Virtual Reality Piloting Pod

### ISSUE THREAD

**Issue by WEKarnesky** [Solaris-Skunk-Werks/solarisskunkwerks#43]
The Virtual Reality Piloting Pod (VRPP) is not currently implemented, as far as I can tell, the construction rules are

> Construction Rules: The VRPP is an alternative form of the torsomounted cockpit from Tactical Operations (see pp. 300-301, TO), but weighs only 3 tons (rather than the 4 tons of a normal torso-mounted cockpit). Also unlike the standard torso-mounted cockpit, a VRPPmodified cockpit places 2 Sensor critical slots in the ’Mech’s head, and places 1 Life Support critical slot each in each of its 3 torso hit locations. The cockpit critical slot is then placed in the center torso.

and found in Interstellar Operations.

Availability of  (E/XXFX), prototype production year of 3052, only available to Battlemechs

**Comment by Maelwys** [comment]
The VRPP is missing its extinction date of 3055 (See pg 39 of IO), and the Introduction section shows "0 ()" next to it.

When you select details and/or the Cost/BV breakdown, the VRPP cost seems to be variable, based on the mech's weight, but page 185 says  

"Virtual Reality Piloting Pod:The VRPP is listed in the Additional Alternate Era Weapons and Equipment Table under Clan Invasion Equipment, and replaces the cost of the unit’s cockpit, rather than adding to it. The costs for the unit’s sensors and life support equipment remain unchanged. " and page 219 has the fixed cost (1,250,000)"

I'm not sure on the BV. Its multiplying it by .95 at the end, which is what I think is the same as a torso-mounted cockpit, but I'm not sure if that's right or not. Page 189 states to multiply the BV by 1.4 to account for the increased skills, but I'm not sure if the cockpit modifier applies as well.

**Comment by WEKarnesky** [comment]
The fix has been merged in.  If/when CGl comments on BV, then open a bug specifically covering the BV calculations.
